### ISSUE TITLE
Не работает в подпапках

### ISSUE THREAD

**Issue by m0hn** [alexey-gamov/aspia-web-update#1]
1. Создал папку `update` в корне на веб сервере (т.е. получился адрес по типу: https://мой_адрес/update)
2. Положил туда файлы центра и открыл https://мой_адрес/update/install.php
3. Заполнил форму и нажал на кнопку "Установить".
4. В результате выходит **ошибка 404** - идет открытие страницы https://мой_адрес/update/update/update.php

Если настроить через файл `config.php` и открыть `index.php`, а дальше ввести логин пароль, то при открытии страницы выдает **ошибку 500**. Если файлы из папки `update` перенести в `корень`, то все прекрасно работает!

_Сервер lighttpd+php7.5+mariadb Debian 11_

**Comment by alexey-gamov** [comment]
Исправлено. Установка теперь возможна в том числе и из подпапок. Спасибо за помощь!)

**Comment by alexey-gamov** [comment]
Исправлено. Установка теперь возможна в том числе и из подпапок. Спасибо за помощь!)
